Algoritmo "Area do triangulo"
// Disciplina   : [ Lógica de Programação com visual G]
// Professor   : Jailson Costa
// Descrição   : Pede o numero e exibe o valor da area do triangulo
// Autor(a)    : Davi
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   base:real
   altura:real
   resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva(" Digite o numero do base do seu triangulo: ")
   leia(base)
   escreva (" Digite o numero da altura do seu triangulo: ")
   leia(altura)
   resultado<- (base * altura / 2)
   escreva(" O valor da aréa do seu triangulo é: ",resultado)
   
Fimalgoritmo