Algoritmo "Area do paralelograma"
// Disciplina   : [ Lógica de Programação com visual G]
// Professor   : Jailson Costa
// Descrição   : Pede o numero e exibe o valor da area do pentagono
// Autor(a)    : Davi
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis
base:real
altura:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 escreva("Digite o valor da base do seu paralelograma: ")
 leia (base)
 escreva("Digite o valor da altura d seu paralelograma: ")
 leia(altura)
 resultado<-(base * altura)
 escreva ("A aréa do seu paralelograma é:", resultado)
 

// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo