Algoritmo "Area do circulo"
// Disciplina   : [ Lógica de Programação com visual G]
// Professor   : Jailson Costa
// Descrição   : Pede o valor do raio e exibe o valor da area do circulo
// Autor(a)    : Davi
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   raio: real
   resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("digite o valor do raio para caucular a area do circulo ")
   leia(raio)
   resultado<-2*3.14*raio
   escreval("o valor da area do circulo é ", resultado)

Fimalgoritmo