Algoritmo "Area do pentagono"
// Disciplina   : [ Lógica de Programação com visual G]
// Professor   : Jailson Costa
// Descrição   : Pede o numero e exibe o valor da area do pentagono
// Autor(a)    : Davi
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis
   lado:real
   altura:real
   resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva(" Digite o numero do lado do seu pentagono: ")
   leia(lado)
   escreva (" Digite o numero da altura do seu pentagono: ")
   leia(resultado)
   resultado<- (lado * resultado *5 )
   escreva(" O valor da aréa do seu pentagono é: ",resultado)


Fimalgoritmo