Algoritmo "Area do quadrado"
// Disciplina   : [ Lógica de Programação com visual G]
// Professor   : Jailson Costa
// Descrição   : Pede o valor do lado e exibe o valor da area do quadrado
// Autor(a)    : Davi
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
    lado:real
    resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva(" Digite o numero do lado do seu quadrado: ")
     leia(lado)
     resultado<- (lado * lado)
     escreva("O valor da aréa do seu quadrado é ",resultado , "cm")

Fimalgoritmo