Algoritmo "DesvioCondicionalEncadeado"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de dezvio condicional em cadeado usando: se, senao
// Autor(a)    : Davi
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual a sua idade?")
leia (idade)
se idade <18 entao
escreval("Voce não pode entrar na casa noturna")
senao
escreval("Pode entrar na casa noturna")
fimse

Fimalgoritmo