Algoritmo "soma"
// Disciplina   : [ Lógica de Programação com visual G ]
// Professor   : Jaildon costa dos santos
// Descrição   : Solicita dois numeros para o usuario,soma e exibi o resultado
// Autor(a)    : Davi Oliveira
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
 numero01:  inteiro
 numero02:  inteiro
 resultado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores
  escreva ("Digite um numero inteiro ")
  leia (numero01)
  escreva ("Digite o segundo numero inteiro ")
  leia (numero02)
  resultado <- numero01/numero02
  escreva ("A divisão dos numeros digitados é : " ,resultado)
Fimalgoritmo