Algoritmo "EstruturaDeRepeticao"
// Disciplina   : [ Lógica de Programação com visual G ]
// Professor   : Jaildon costa dos santos
// Descrição   : Faz um laço de repeitção
// Autor(a)    : Davi Oliveira
// Data atual  : 08/04/2026
Var
// Seção de Declarações das variáveis 
    contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto contadora <10 faça
   escreval("Davi")
   contadora <- contadora + 1
   fimenquanto

Fimalgoritmo