Algoritmo "LacoPara"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor: Davi
// Data atual  : 13/04/2026

Var
   // Seção de Declarações das variáveis
   contadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 ate 10 passo 1 faca
        escreval("Davi")
         fimpara

Fimalgoritmo