Algoritmo "Repita"

// Disciplina  :[Lógica de Programação com VisualG]

// Professor   :Jailson Costa dos Santos

// Descrição   : Exemplo de laço de repetição repita

// Autor(a)    : obama

// Data atual  : 13/04/2026

Var

   // Seção de Declarações das variáveis

   contadora:inteiro

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...

   repita
   Escreval("Jailson")
   contadora<-contadora+1
   ate contadora>9


Fimalgoritmo
