Algoritmo "semnome"
// Disciplina   : [ Lógica de Programação com Visual G ]
// Professor   : Jailson costa dos santos
// Descrição   : Solicita o nome da pessoa e da boas vindas
// Autor(a)    : Davi Oiveira
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
   nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores
   escreva("Qual o seu nome?  ")
   leia(nome)
   escreva(nome," seja bem vindo")

Fimalgoritmo